
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "influxdb"
  namespace: "kube-system"
  labels:
    app: "influxdb"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: "influxdb"
        name: "influxdb"
        app: "influxdb"
    spec:
      containers:
        - name: "influxdb"
          image: "influxdb:0.13.0"
          ports:
            - containerPort: 8083
            - containerPort: 8086
          env:
            - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
              value: "true"
          imagePullPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: kube-system
  labels:
    app: influxdb
spec:
  type: "LoadBalancer"
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
    name: external
  - port: 8083
    protocol: TCP
    targetPort: 8083
    name: admin
  selector:
    app: influxdb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
