apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: test-events
  name: no-events
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: no-events
rules:
- apiGroups: ["*"]
  resources: ["nodes", "daemonsets", "deployments", "pods", "jobs", "replicasets", "replicationcontrollers", "statefulsets", "services", "configmaps", "namespaces", "persistentvolumes", "storageclasses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: no-events
  labels:
    app: no-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: no-events
subjects:
- kind: ServiceAccount
  name: no-events
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: test-namespace
  name: default-ns
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: default-ns
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["daemonsets", "deployments", "pods", "jobs", "replicasets", "replicationcontrollers", "statefulsets", "services", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  resourceNames: ["default"]
  verbs: ["get", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: only-nodes
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
# This role binding allows "dave" to read secrets in the "development" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-ns-binding
  namespace: default # This only grants permissions within the "development" namespace.
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-ns
subjects:
  - kind: ServiceAccount
    name: default-ns
    namespace: default

# roleRef:
#   kind: ClusterRole
#   name: only-nodes
#   apiGroup: rbac.authorization.k8s.io
