apiVersion: v1
kind: ServiceAccount
metadata:
  name: full-access
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-access-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: full-access
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
