kind: Namespace
apiVersion: v1
metadata:
  name: with-quota
  labels:
    name: with-quota

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: with-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
