apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: no-events
  name: no-events
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: no-events
rules:
- apiGroups: ["*"]
  resources: ["nodes", "daemonsets", "deployments", "pods", "jobs", "replicasets", "replicationcontrollers", "statefulsets", "services", "configmaps", "namespaces", "persistentvolumes", "storageclasses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: no-events
  labels:
    app: no-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: no-events
subjects:
- kind: ServiceAccount
  name: no-events
  namespace: default
